sudo: false
language: generic

addon:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - bash -n unix/.bashrc
  - shellcheck -s bash -e SC2142 -e SC2154 -e SC2139 unix/.bashrc

notifications:
  email: false
