sudo: false
language: generic

addon:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - bash -n unix/.bashrc
  - shellcheck unix/.bashrc

notifications:
  email: false
