git:
  quiet: true

language: minimal

services:
  - docker

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - powershell
          sources:
            - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main'
              key_url: 'https://packages.microsoft.com/keys/microsoft.asc'

install: ci/install.sh
script: ci/test.sh

notifications:
  email: false
